/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grupp10.admin;

import grupp10.utility.DatabaseHandler;
import grupp10.utility.Validation;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Axel
 */
public class ChangeUserInfo extends javax.swing.JFrame {

    /**
     * Creates new form ChangeUserInfo
     */
    public ChangeUserInfo() {
        initComponents();
        fillComboBox();
        cbYesNo.setVisible(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbOption = new javax.swing.JComboBox<>();
        txtNewInfo = new javax.swing.JTextField();
        btnChangeInfo = new javax.swing.JButton();
        cbUser = new javax.swing.JComboBox<>();
        lblUsername = new javax.swing.JLabel();
        lblFirstname = new javax.swing.JLabel();
        lblSurname = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblTitel = new javax.swing.JLabel();
        lblRoomNumber = new javax.swing.JLabel();
        lblAdmin = new javax.swing.JLabel();
        lblUsername1 = new javax.swing.JLabel();
        lblFirstname1 = new javax.swing.JLabel();
        lblSurname1 = new javax.swing.JLabel();
        lblEmail1 = new javax.swing.JLabel();
        lblTitel1 = new javax.swing.JLabel();
        lblRoomNumber1 = new javax.swing.JLabel();
        lblAdmin1 = new javax.swing.JLabel();
        cbYesNo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Användarnamn", "Lösenord", "Förnamn", "Efternamn", "Email", "Titel", "Rumsnummer", "Admintillstånd" }));
        cbOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOptionActionPerformed(evt);
            }
        });

        btnChangeInfo.setText("Ändra");
        btnChangeInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeInfoActionPerformed(evt);
            }
        });

        cbUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbUserActionPerformed(evt);
            }
        });

        lblUsername.setText(" ");

        lblFirstname.setText(" ");

        lblSurname.setText(" ");

        lblEmail.setText(" ");

        lblTitel.setText(" ");

        lblRoomNumber.setText(" ");

        lblUsername1.setText("Användarnamn");

        lblFirstname1.setText("Förnamn");

        lblSurname1.setText("Efternamn");

        lblEmail1.setText("Email");

        lblTitel1.setText("Titel");

        lblRoomNumber1.setText("Rumsnummer");

        lblAdmin1.setText("Admintillstånd");

        cbYesNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ja", "Nej" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblRoomNumber1)
                                            .addGap(8, 8, 8))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(lblEmail1)
                                            .addGap(69, 69, 69)))
                                    .addComponent(lblFirstname1)
                                    .addComponent(lblAdmin1)
                                    .addComponent(lblTitel1)
                                    .addComponent(lblSurname1)
                                    .addComponent(lblUsername1))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lblTitel, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                            .addComponent(lblSurname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblFirstname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblRoomNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                                        .addComponent(cbYesNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnChangeInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(78, 78, 78))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbOption, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNewInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 111, Short.MAX_VALUE)
                .addComponent(cbUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUsername1)
                        .addGap(28, 28, 28)
                        .addComponent(lblFirstname1)
                        .addGap(21, 21, 21)
                        .addComponent(lblSurname1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEmail1)
                                .addGap(27, 27, 27)
                                .addComponent(lblTitel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(lblRoomNumber1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(lblRoomNumber))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(lblEmail)
                        .addGap(27, 27, 27)
                        .addComponent(lblTitel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUsername)
                        .addGap(28, 28, 28)
                        .addComponent(lblFirstname)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSurname)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNewInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnChangeInfo)
                            .addComponent(cbYesNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAdmin1)
                    .addComponent(lblAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangeInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeInfoActionPerformed
        String cbstring = cbUser.getSelectedItem().toString();
        int i = cbstring.indexOf(".");
        String username = cbstring.substring(0, i);
        if(!cbstring.contains("Välj.")){
        if(Validation.textfieldNotEmpty(txtNewInfo, "Fyll i ny information.")){
            String newInfo = txtNewInfo.getText();
            String cb = cbOption.getSelectedItem().toString();
                if(cb.contains("Användarnamn")){
                    String sql2 = "Select Anvandarnamn from larare where anvandarnamn ='"+newInfo+"';";
                    String checkNewUser = DatabaseHandler.fetchSingle(sql2);
                    if(checkNewUser.isEmpty() && Validation.hasOnlyLetters(newInfo) && newInfo.length() > 3 && newInfo.length() < 41){
                        String sql3 = "Update larare set Anvandarnamn = '"+newInfo+"' where Anvandarnamn = '"+username+"';";
                        DatabaseHandler.update(sql3);
                        JOptionPane.showMessageDialog(null, "Användarnamnet har ändrats!");
                    }
                    else{
                    JOptionPane.showMessageDialog(null, "Fyll i det nya användarnamnet rätt.");
                    }
                }
                if(cb.contains("Lösenord")){
                    if(newInfo.length() > 5 && newInfo.length() < 41){
                        String sql3 = "Update larare set Losenord = '"+newInfo+"' where Anvandarnamn = '"+username+"';";
                        DatabaseHandler.update(sql3);
                        JOptionPane.showMessageDialog(null, "Lösenordet har ändrats!");
                    }
                    else{
                    JOptionPane.showMessageDialog(null, "Fyll i det nya lösenordet rätt. Måste vara mellan 6 och 39 tecken.");
                    }
                }
                if(cb.contains("Förnamn")){
                    if(Validation.hasOnlyLetters(newInfo) && newInfo.length() > 2 && newInfo.length() < 41){
                        String sql3 = "Update larare set Fornamn = '"+newInfo+"' where Anvandarnamn = '"+username+"';";
                        DatabaseHandler.update(sql3);
                        JOptionPane.showMessageDialog(null, "Förnamnet har ändrats!");
                    }
                    else{
                    JOptionPane.showMessageDialog(null, "Fyll i det nya förnamnet rätt. Inga siffror.");
                    }
                }
                if(cb.contains("Efternamn")){
                    if(Validation.hasOnlyLetters(newInfo) && newInfo.length() > 2 && newInfo.length() < 41){
                        String sql3 = "Update larare set Efternamn = '"+newInfo+"' where Anvandarnamn = '"+username+"';";
                        DatabaseHandler.update(sql3);
                        JOptionPane.showMessageDialog(null, "Efternamnet har ändrats!");
                    }
                    else{
                    JOptionPane.showMessageDialog(null, "Fyll i det nya efternamnet rätt. Inga siffror.");
                    }
                }
                if(cb.contains("Email")){
                    if(newInfo.contains("@") && !newInfo.startsWith("@") && !newInfo.endsWith("@") && newInfo.length() < 41){
                        String sql3 = "Update larare set Email = '"+newInfo+"' where Anvandarnamn = '"+username+"';";
                        DatabaseHandler.update(sql3);
                        JOptionPane.showMessageDialog(null, "Emailen har ändrats!");
                    }
                    else{
                    JOptionPane.showMessageDialog(null, "Fyll i det nya Emailadressen rätt.");
                    }
                }
                if(cb.contains("Titel")){
                    if(Validation.hasOnlyLetters(newInfo) && newInfo.length() < 41){
                        String sql3 = "Update larare set Titel = '"+newInfo+"' where Anvandarnamn = '"+username+"';";
                        DatabaseHandler.update(sql3);
                        JOptionPane.showMessageDialog(null, "Titeln har ändrats!");
                    }
                    else{
                    JOptionPane.showMessageDialog(null, "Fyll i det nya titeln rätt. Endast bokstäver");
                    }
                }
                if(cb.contains("Rumsnummer")){
                    if(newInfo.length() < 41){
                        String sql3 = "Update larare set Rumsnummer = '"+newInfo+"' where Anvandarnamn = '"+username+"';";
                        DatabaseHandler.update(sql3);
                        JOptionPane.showMessageDialog(null, "Rumsnummert har ändrats!");
                    }
                    else{
                    JOptionPane.showMessageDialog(null, "Fyll i det nya rumsnummert rätt.");
                    }
                }
                if(cb.contains("Admintillstånd")){
                    String yesno = cbYesNo.getSelectedItem().toString();
                    if(yesno.contains("Ja")){
                        String sql3 = "Update larare set IsAdmin = 1 where Anvandarnamn = '"+username+"';";
                        DatabaseHandler.update(sql3);
                        JOptionPane.showMessageDialog(null, "Användaren har nu administrationsbehörighet!");
                    }
                    else if(yesno.contains("Nej")){
                        String sql4 = "Update larare set IsAdmin = 0 where Anvandarnamn = '"+username+"';";
                        DatabaseHandler.update(sql4);
                        JOptionPane.showMessageDialog(null, "Användaren har nu inte administrationsbehörighet!");
                    }
                }
        }
        }
        else{
        JOptionPane.showMessageDialog(null, "Välj en lärare.");}
        
    }//GEN-LAST:event_btnChangeInfoActionPerformed

    private void cbUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbUserActionPerformed
        String cbstring = cbUser.getSelectedItem().toString();
        int i = cbstring.indexOf(".");
        String user = cbstring.substring(0, i);
        String username = DatabaseHandler.fetchSingle("select anvandarnamn from larare where anvandarnamn ='"+user+"'");
        String firstname = DatabaseHandler.fetchSingle("select fornamn from larare where anvandarnamn ='"+user+"'");
        String surname = DatabaseHandler.fetchSingle("select efternamn from larare where anvandarnamn ='"+user+"'");
        String email = DatabaseHandler.fetchSingle("select email from larare where anvandarnamn ='"+user+"'");
        String title = DatabaseHandler.fetchSingle("select titel from larare where anvandarnamn ='"+user+"'");
        String roomnumber = DatabaseHandler.fetchSingle("select rumsnummer from larare where anvandarnamn ='"+user+"'");
        String admin = DatabaseHandler.fetchSingle("select isadmin from larare where anvandarnamn ='"+user+"'");
        
        lblUsername.setText(username);
        lblFirstname.setText(firstname);
        lblSurname.setText(surname);
        lblEmail.setText(email);
        lblTitel.setText(title);
        lblRoomNumber.setText(roomnumber);
        
        if(admin.equals("1")){
            lblAdmin.setText("Ja");
        }
        else if(admin.equals("0")){
            lblAdmin.setText("Nej");
        }
    }//GEN-LAST:event_cbUserActionPerformed

    private void cbOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOptionActionPerformed
        // TODO add your handling code here:
        if(cbOption.getSelectedItem().equals("Admintillstånd"))
        {
            txtNewInfo.setText("hej");
            cbYesNo.setVisible(true);
            txtNewInfo.setVisible(false);
        }
        else
        {
            txtNewInfo.setText("");
            cbYesNo.setVisible(false);
            txtNewInfo.setVisible(true);
        }
    }//GEN-LAST:event_cbOptionActionPerformed

    
    private void fillComboBox()
    {
        DefaultComboBoxModel cbBox = new DefaultComboBoxModel();
        cbUser.addItem("Välj.");
        String sql = "Select ANVANDARNAMN, FORNAMN, EFTERNAMN from larare;";
        ArrayList<HashMap<String, String>> user = DatabaseHandler.fetchRows(sql);
        for(HashMap<String, String> names : user){
            String s = names.get("ANVANDARNAMN")+ ". "+names.get("FORNAMN")+" "+names.get("EFTERNAMN");
            cbBox.addElement(s);
            System.out.println(s);
            cbUser.addItem(s);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeUserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeUserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeUserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeUserInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangeUserInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangeInfo;
    private javax.swing.JComboBox<String> cbOption;
    private javax.swing.JComboBox<String> cbUser;
    private javax.swing.JComboBox<String> cbYesNo;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblAdmin1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmail1;
    private javax.swing.JLabel lblFirstname;
    private javax.swing.JLabel lblFirstname1;
    private javax.swing.JLabel lblRoomNumber;
    private javax.swing.JLabel lblRoomNumber1;
    private javax.swing.JLabel lblSurname;
    private javax.swing.JLabel lblSurname1;
    private javax.swing.JLabel lblTitel;
    private javax.swing.JLabel lblTitel1;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsername1;
    private javax.swing.JTextField txtNewInfo;
    // End of variables declaration//GEN-END:variables
}
