/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grupp10;

import grupp10.utility.DatabaseHandler;
import grupp10.utility.Validation;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author Axel
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        // lazy
        txtfAnvandarnamn.setText("asan");
        pwfLosenord.setText("anders123");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogin = new javax.swing.JToggleButton();
        txtfAnvandarnamn = new javax.swing.JTextField();
        pwfLosenord = new javax.swing.JPasswordField();
        lblUsername = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLogin.setText("Logga in");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblUsername.setText("Användarnamn");

        jLabel1.setText("Lösenord");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogin)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsername)
                            .addComponent(jLabel1))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pwfLosenord, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(txtfAnvandarnamn))))
                .addGap(130, 130, 130))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfAnvandarnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsername))
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(pwfLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(btnLogin)
                .addGap(135, 135, 135))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /*private boolean checkAdmin(String kontroll)
    {
        
        boolean loginSucceded = false;
        for (HashMap<String, String> row : usernameAndPassword) {
            if (row.get("Anvandarnamn").equals(username)) {
                if(row.get("Losenord").equals(password)){
                    System.out.println("Lösenord finns");
                    loginSucceded = true;
                }
            }
        }
        return loginSucceded;
    }*/
    
    /**
     * Check if user input exist in the database.
     * @param username the username of the logged in user.
     * @param password the password of the logged in user.
     * @return a boolean whether the username and password matches.
     */
    private boolean checkLogin(String username, String password)
    {
        ArrayList<HashMap<String, String>> usernameAndPassword = DatabaseHandler.fetchRows("Select Anvandarnamn, Losenord from Larare");
        
        boolean loginSucceded = false;
        for (HashMap<String, String> row : usernameAndPassword) {
            if (row.get("Anvandarnamn").equals(username)) {
                if(row.get("Losenord").equals(password)){
                    loginSucceded = true;
                }
            }
        }
        return loginSucceded;
    }
    
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String username = txtfAnvandarnamn.getText();
        String password = pwfLosenord.getText();
        String sql = "Select isAdmin from Larare where Anvandarnamn = '"+username+"'";
            if(Validation.textfieldNotEmpty(txtfAnvandarnamn, "Användarnamnfältet är tomt") && Validation.textfieldNotEmpty(pwfLosenord, "Lösenordfältet är tomt.")) {
                if(checkLogin(username, password)) {
                    String isadmin = DatabaseHandler.fetchSingle(sql);
                    if(isadmin.equals("1")){
                        addInfoToUser(username);
                        this.setVisible(false);
                        new MainGUI().setVisible(true);
                    } else {
                        addInfoToUser(username);
                        this.setVisible(false);
                        new MainGUI().setVisible(true);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Fel lösenord eller användarnamn.");
                }
            }
    }//GEN-LAST:event_btnLoginActionPerformed
    
    private void addInfoToUser(String username)
    {

        ArrayList<HashMap<String, String>> user = DatabaseHandler.fetchRows("select * from Larare where anvandarnamn = '" + username + "'");
        
        for(HashMap<String, String> anvandare : user)
        {
            User.username = username;
            User.id = anvandare.get("Id");
            User.fullName = anvandare.get("Fornamn") + " " + anvandare.get("Efternamn");
            if(anvandare.get("isAdmin").equals("1"))
            {
                User.isAdmin = true;
            }
            else{
                User.isAdmin = false;
            } 
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField pwfLosenord;
    private javax.swing.JTextField txtfAnvandarnamn;
    // End of variables declaration//GEN-END:variables
}