package grupp10;

import grupp10.admin.ChangeUserInfo;
import grupp10.admin.RegisterUser;
import grupp10.formellabloggen.*;
import grupp10.imagehandler.ImageHandler;
import grupp10.informellabloggen.InformellaBloggen;
import grupp10.user.ChangePassword;
import grupp10.utility.DatabaseHandler;

/**
 * Main window
 * @author rober
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
//        String id = DatabaseHandler.insertGetId("insert into larare (Id, Anvandarnamn, Losenord, Fornamn, Efternamn, Email, Titel, Rumsnummer, isAdmin, isDeleted) " +
//                                                "values (default, 'aaaaa', 'a', 'a', 'a', 'aaaa@ad', 'titel', 'n20', false, false)");
//        System.out.println("id: " + id);
        
//        ImageHandler imageHandler = new ImageHandler();
//        String path = imageHandler.fileChooser(this);
//        
//        if (!path.equals("")) {
//            imageHandler.uploadImageToBlog("1", "Hello", path);
//            imageHandler.displayImage("1", lblImage, lblBildtext);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFormellaBloggen = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();
        lblBildtext = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemRegistreraAnvandare = new javax.swing.JMenuItem();
        menuItemAndraInformationOmAnvandare = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lärarbloggen - Startsida");

        btnFormellaBloggen.setText("Formella bloggen");
        btnFormellaBloggen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormellaBloggenActionPerformed(evt);
            }
        });

        jMenu1.setText("Arkiv");

        jMenuItem2.setText("Byt lösenord");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setText("Avsluta");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Admin");

        menuItemRegistreraAnvandare.setText("Registrera användare");
        menuItemRegistreraAnvandare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRegistreraAnvandareActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemRegistreraAnvandare);

        menuItemAndraInformationOmAnvandare.setText("Ändra information om användare");
        menuItemAndraInformationOmAnvandare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAndraInformationOmAnvandareActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemAndraInformationOmAnvandare);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(btnFormellaBloggen))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBildtext, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))))
                .addContainerGap(385, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBildtext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(btnFormellaBloggen)
                .addGap(214, 214, 214))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new ChangePassword().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnFormellaBloggenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormellaBloggenActionPerformed
        new FormellaBloggen().setVisible(true);
    }//GEN-LAST:event_btnFormellaBloggenActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuItemRegistreraAnvandareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRegistreraAnvandareActionPerformed
        new RegisterUser().setVisible(true);
    }//GEN-LAST:event_menuItemRegistreraAnvandareActionPerformed

    private void menuItemAndraInformationOmAnvandareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAndraInformationOmAnvandareActionPerformed
        new ChangeUserInfo().setVisible(true);
    }//GEN-LAST:event_menuItemAndraInformationOmAnvandareActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFormellaBloggen;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel lblBildtext;
    private javax.swing.JLabel lblImage;
    private javax.swing.JMenuItem menuItemAndraInformationOmAnvandare;
    private javax.swing.JMenuItem menuItemRegistreraAnvandare;
    // End of variables declaration//GEN-END:variables
}
